//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyGuide.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10,4")]
        public global::System.Windows.Size RowsColumns {
            get {
                return ((global::System.Windows.Size)(this["RowsColumns"]));
            }
            set {
                this["RowsColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("submitted_on")]
        public global::DAL.PostOrderBy PostOrderByColumn {
            get {
                return ((global::DAL.PostOrderBy)(this["PostOrderByColumn"]));
            }
            set {
                this["PostOrderByColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("created_at")]
        public global::DAL.PoolOrderBy PoolOrderByColumn {
            get {
                return ((global::DAL.PoolOrderBy)(this["PoolOrderByColumn"]));
            }
            set {
                this["PoolOrderByColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ASC")]
        public global::DAL.OrderMode PostOrderMode {
            get {
                return ((global::DAL.OrderMode)(this["PostOrderMode"]));
            }
            set {
                this["PostOrderMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ASC")]
        public global::DAL.OrderMode PoolOrderMode {
            get {
                return ((global::DAL.OrderMode)(this["PoolOrderMode"]));
            }
            set {
                this["PoolOrderMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n                    <ArrayOfSite xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-in" +
            "stance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n                        <" +
            "Site>Yande</Site>\r\n                    </ArrayOfSite>\r\n                ")]
        public DAL.Site[] SiteSelected {
            get {
                return ((DAL.Site[])(this["SiteSelected"]));
            }
            set {
                this["SiteSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n                    <ArrayOfRating xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-" +
            "instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n                       " +
            " <Rating>Safe</Rating>\r\n                    </ArrayOfRating>\r\n                ")]
        public DAL.Rating[] RatingSelected {
            get {
                return ((DAL.Rating[])(this["RatingSelected"]));
            }
            set {
                this["RatingSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                    <ArrayOfPrefer xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
                        <Prefer>Good</Prefer>
                        <Prefer>Normal</Prefer>
                    </ArrayOfPrefer>
                ")]
        public DAL.Prefer[] PreferSelected {
            get {
                return ((DAL.Prefer[])(this["PreferSelected"]));
            }
            set {
                this["PreferSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageFolder {
            get {
                return ((string)(this["ImageFolder"]));
            }
            set {
                this["ImageFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280")]
        public double PostInfoWindowWidth {
            get {
                return ((double)(this["PostInfoWindowWidth"]));
            }
            set {
                this["PostInfoWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double PostInfoWindowHeight {
            get {
                return ((double)(this["PostInfoWindowHeight"]));
            }
            set {
                this["PostInfoWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState PostInfoWindowState {
            get {
                return ((global::System.Windows.WindowState)(this["PostInfoWindowState"]));
            }
            set {
                this["PostInfoWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StatusFolder {
            get {
                return ((string)(this["StatusFolder"]));
            }
            set {
                this["StatusFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280")]
        public double MainWindowWidth {
            get {
                return ((double)(this["MainWindowWidth"]));
            }
            set {
                this["MainWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double MainWindowHeight {
            get {
                return ((double)(this["MainWindowHeight"]));
            }
            set {
                this["MainWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState MainWindowState {
            get {
                return ((global::System.Windows.WindowState)(this["MainWindowState"]));
            }
            set {
                this["MainWindowState"] = value;
            }
        }
    }
}
